[package]
name = "dolrs"
version = "0.1.0"
authors = ["Dennis Seller <d.seller93@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
simple_logger = "1.9.0"
minifb = "0.19.1"
peg = "0.6.3"
